### ISSUE TITLE
TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by dyyybek** [huertatipografica/HTLetterspacer#33] opened 2016-12-23 12:31 UTC
I'm trying to run the script with the example files but i get this:

```
Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 231, in <module>
    HTLetterspacerScript()
  File "HT_LetterSpacer_UI.py", line 66, in __init__
    self.mySelection = list(set(selectedLayers))
TypeError: 'list' object is not callable
```

**Comment by andrestelex** [comment] 2016-12-23 19:46
I can't reproduce the same error, but if on the tab view I don't select anything and put the cursor at the end of the text (string) line, I get this:

```
Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 231, in <module>
    HTLetterspacerScript()
  File "HT_LetterSpacer_UI.py", line 68, in __init__
    self.layerID = self.mySelection[0].associatedMasterId
IndexError: list index out of range
```

Are you selecting anything? Can you describe when do you see this error?

**Comment by Txonliz** [comment] 2017-01-12 23:50
I get a similar error in every file I tried other than ExampleFont.glyphs
`Traceback (most recent call last):`
`  File "<string>", line 231, in <module>`
`  File "<string>", line 70, in __init__`
`  File "<string>", line 51, in readConfig`
`IndexError: list index out of range`

**Comment by impallari** [comment] 2017-04-11 23:20
I'm getting the same errors ;(
![screen shot 2017-04-11 at 20 11 58](https://cloud.githubusercontent.com/assets/3036973/24934806/49a4933c-1ef4-11e7-95fb-a234090b994a.png)

**Comment by impallari** [comment] 2017-04-11 23:44
Fond the problem... in "defaultConfigFile.py" you need to delete lines #1 and #2, that's all.
https://github.com/huertatipografica/HTLetterspacer/blob/master/defaultConfigFile.py#L1-L2

**Comment by andrestelex** [comment] 2018-05-01 23:48
This is fixed in last version. It was due to an empty selection (usually end of a line in preview tab)

**Closed by andrestelex** 2018-05-01 23:48 UTC
