### ISSUE TITLE
Support Glyphs3?

### ISSUE THREAD

**Issue by dharmatype** [huertatipografica/HTLetterspacer#55] opened 2020-11-17 23:13 UTC
Hello
Does HTLetterspacer support Glyphs version3?
I and many designers gladly pay for that.
HTLetterspacer is an awesome tool.

**Comment by jpt** [comment] 2020-11-18 01:59
I took as look into this too as I do not believe it currently works in Glyphs 3.

Some steps I took before giving up on `HT_LetterSpacer_script.py`:

Line 22, change `from objectsGS import *` to `import objectsGS`

I think those `lefty` and `righty` variables need to be global, or re-scoped.

But from there I ran into the `AttributeError: 'HTLetterpacerLib' object has no attribute 'factor'` referenced in #54, and ran out of time 🙂 

Happy to help with this if anyone has a better sense of what's going on

**Comment by juandelperal** [comment] 2020-11-20 10:48
Thanks @dharmatype and @jpt 
At least in my setup I see that the script uses some libraries (like numpy) but not included in Glyphs 3's environment.
I will take a look

**Comment by juandelperal** [comment] 2020-11-20 10:49
Maybe @mekkablue can help us ;)

**Comment by jpt** [comment] 2020-11-22 06:38
> Thanks @dharmatype and @jpt
> At least in my setup I see that the script uses some libraries (like numpy) but not included in Glyphs 3's environment.
> I will take a look

With Glyphs 3 you can use whatever environment you want so that shouldn't strictly block progress

<img width="625" alt="Screen Shot 2020-11-21 at 10 33 49 PM" src="https://user-images.githubusercontent.com/5319916/99896930-efa90b80-2c49-11eb-9721-d4b6870ec6c9.png">

I'll take another look soon too

**Comment by dharmatype** [comment] 2020-11-23 07:32
I installed Python3.9 from python.com and selected in Glyphs3.0. As a result, Glyphs cannot start.
Reinstall GLyphs 3.0 <--NOW!

**Comment by kresdjan** [comment] 2020-12-21 06:01
I can't get it working with Glyphs 3 either. I've installed **Python** and **Vanilla** through Glyphs' Plugin Manager. When I installed the **HT Letterspacer** script and restart glyphs, launch the HT Letterspacer UI nothing happens and the Micro Panel output:

```
Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 8
    import HT_LetterSpacer_script
  File "HT_LetterSpacer_script.py", line 19
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by jpt** [comment] 2020-12-21 06:35
@kresdjan - you will need to install a different python3 environment in which to install numpy. [homebrew](https://brew.sh/) is the best option on a mac. then you can run `brew install numpy` from your terminal and set glyphs to use your new python install.

unfortunately, this won't fix all the problems. 

in addition to some of the things I mentioned earlier in this issue, there are some other python3 changes that need to happen

for example, `HT_Letterspacer.py` and `HT_Letterspacer_UI.py` both use the `reload()` function which is not included in python3 - those files will need `from importlib import reload`.

the issue I ran into earlier - `AttributeError: 'HTLetterpacerLib' object has no attribute 'factor'` — can be solved by explicitly initializing the script with a factor value, but I don't know what that number should be by default (I just gave it a value of `1` to see what would happen)

<img width="344" alt="Screen Shot 2020-12-20 at 10 28 57 PM" src="https://user-images.githubusercontent.com/5319916/102746303-de1f5600-4312-11eb-812d-28265b129131.png">

This `factor` variable is the last bit to fix that isn't a straightforward python2->python3 problem, again as I'm unsure of its role in the script. In other words, I've gotten HTLetterspacer running in Glyphs 3, and it works, but I'm not sure if it works correctly. 

I don't have a ton of free time right now and can look into this more in a couple of weeks if no one else gets to it first.

**Comment by mekkablue** [comment] 2020-12-21 08:55
We (@schriftgestalt and I) have been considering adding numpy to the Python3 installation in Plugin Manager, like we included PyObjC. That could solve the installation hurdle.

Alternative: is there a way to rewrite it without numpy?

**Comment by jpt** [comment] 2020-12-22 09:08
yes, it only uses `numpy.arrage()` which I think is just an equal steps affine transformation. I'm pretty sure I have some code lying around to do that.

**Comment by jpt** [comment] 2020-12-22 11:28
ok, I have created a branch at [issue-55-glyphs3](/huertatipografica/HTLetterspacer/tree/issue-55-glyphs3) (work in progress). this branch removes numpy as a dependency, and fixes a few python2->python3 things, but still has problems  if anyone wants to help with the `lefty`, `righty`, and `factor` initialization errors.

**Comment by mekkablue** [comment] 2021-01-11 12:55
Yes that is the way to go. `numpy` is quite a lot to import, just for that one line.

Shall I link the Plugin Manager to that branch or will you pull it into the main branch?

**Comment by andrestelex** [comment] 2021-01-11 14:03
Thanks for the work. I was testing the new branch and it doesn't work for Glyphs 2.

```
Traceback (most recent call last):
  File "HT_LetterSpacer.py", line 9, in <module>
    from importlib import reload
ImportError: cannot import name reload
```

**Comment by schriftgestalt** [comment] 2021-01-11 20:23
I have send a pull request to silence this.

**Comment by mekkablue** [comment] 2021-01-12 17:09
OK, switched the Plugin Manager entry to the `issue-55-glyphs3` branch.

**Comment by davelab6** [comment] 2021-01-13 04:30
What's needed for a PR to be made and merged and a new release tagged?

**Comment by jpt** [comment] 2021-01-13 08:15
Yeah better to merge G3 work into master than change where the Plug-in Manager looks. I made that branch as a starting point in case others wanted to jump in as I’ve been short on time, but I don’t think anyone else has looked at it. there are still Python 2/3 issues on that branch to resolve:

- Glyphs 2 and 3 support (supporting both shouldn’t be bad, just changing the way objectGS is imported and how reload is called, depending)
- Fixing the way factor, left, right, lefty, righty variables are scoped and what their default values should be (I only got the glyphs 3 branch as far as removing numpy and breaking here instead of on init :))

**Comment by madig** [comment] 2021-01-23 18:48
The `np.arange` call can be replaced by a simple `for ii in range(-1, len(points) - 1):`.

**Comment by madig** [comment] 2021-01-23 20:45
https://github.com/huertatipografica/HTLetterspacer/pull/60

**Comment by jpt** [comment] 2021-01-24 06:38
> #60

unfortunately while this runs in G3 (after fixing up some print vs print() stuff), it doesn't seem like it's working as intended. as I mentioned in the PR, I'm happy to keep testing. for whatever reason, giving lefty, righty, and factor defaults doesn't accomplish what I would expect. I will take a closer look tomorrow to see if there's anything to combine from different efforts on this issue

**Comment by madig** [comment] 2021-01-24 09:36
Can you make a test font with just one glyph that triggers the issue?

**Comment by jpt** [comment] 2021-01-25 00:55
happy to! I wonder if it is related to components being present in the font I tested on, I will update soon with some screenshots etc

**Comment by madig** [comment] 2021-01-25 10:45
Ah, components. Yeah I can see that triggering something. Are those compoennts not autoaligned in your font? Those should be skipped.

**Comment by jpt** [comment] 2021-01-31 06:25
@madig @andrestelex #60 broke the ability to run in Glyphs 3. 

First I get this:

```
Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 15
    HT_LetterSpacer_script.HTLetterspacerScript(ui=True)
TypeError: __init__() missing 1 required positional argument: 'drawAreas'
```

So, if I change that line to `HT_LetterSpacer_script.HTLetterspacerScript(ui=True,drawAreas=False)`

And change `print self.angle` to `print(self.angle)`

I now get:

```
Traceback (most recent call last):
  File "HT_LetterSpacer_UI.py", line 15
    HT_LetterSpacer_script.HTLetterspacerScript(ui=True,drawAreas=False)
  File "HT_LetterSpacer_script.py", line 446, in __init__
    self.config = readConfig(self.master.name)
  File "HT_LetterSpacer_script.py", line 118, in readConfig
    newFile.write(defaultConfigFile)
TypeError: write() argument must be str, not module
```

**Comment by jpt** [comment] 2021-01-31 21:43
If a test font is needed, try [work sans](https://raw.githubusercontent.com/weiweihuanghuang/Work-Sans/master/sources/WorkSans.glyphs) - same issue, different results in G2 and G3

**Comment by andrestelex** [comment] 2021-01-31 22:31
Can you try dev branch?

**Comment by andrestelex** [comment] 2021-02-01 00:19
I'm testing dev branch with updates. Glyphs 2 works great. Here is a screenshot of the generated areas
![image](https://user-images.githubusercontent.com/5502786/106402663-73d5f700-6422-11eb-9538-8c68f398bd96.png)

But in Glyphs 3, the measurements don't work
![image](https://user-images.githubusercontent.com/5502786/106402690-99fb9700-6422-11eb-9be4-5409e90cc586.png)

That weird spaces you see, plus the gaps on the H are something I don't know. It's exactly the same script.
However, I remember seeing something like this years ago, and we solved it. But I don't remember what changed then.

I think there is something wrong with this function
```

def getMargins(layer, y):
	startPoint = NSMakePoint(NSMinX(layer.bounds), y)
	endPoint = NSMakePoint(NSMaxX(layer.bounds), y)

	result = layer.calculateIntersectionsStartPoint_endPoint_(startPoint, endPoint)
	count = len(result)
	if (count <= 2):
		return (None, None)

	left = 1
	right = count - 2
	return (result[left].pointValue().x, result[right].pointValue().x)


```

Any ideas @mekkablue ?

**Comment by jpt** [comment] 2021-06-14 04:55
@andrestelex I wonder what would happen if it used [`intersectionBetweenPoints`](https://docu.glyphsapp.com/#GSLayer.intersectionsBetweenPoints) instead of `calculateIntersectionsStartPoint_endPoint_`?

**Comment by schriftgestalt** [comment] 2021-06-14 13:07
Both should return the same thing (the method you liked to is just calling the other). And running that in Glyphs 2 and 3 returner the same result.

**Comment by schriftgestalt** [comment] 2021-08-11 08:02
I fixed the remaining issues. Could someone add me to the repo that I can push directly?

**Comment by schriftgestalt** [comment] 2021-08-11 08:34
Thanks. I made a new branch (glyphs3) because the code is not compatible with Glyphs 2 any more. I updated the entry in the Plugin Manager (one might need to remove and re-install to get the new version). 

And the config files need to be updated. There is a new column that holds the "case" (the case is not stored in the subCategory any more).

**Closed** 2021-08-11 20:35 UTC

**Comment by jpt** [comment] 2021-08-15 22:32
@schriftgestalt This works if you manually install the script and check out to the `glyphs3` branch, but even after installing and uninstalling from the plugin manager, it stays on the main (Glyphs 2) branch and does not work correctly.

**Comment by schriftgestalt** [comment] 2021-08-15 23:46
The glyphs3 branch is only for Glyphs3, not for Glyphs2. You might need to apply some of the changes to the main branch, too. 
I only worked on and tested in Glyphs 3.

**Comment by jpt** [comment] 2021-08-16 01:07
Sorry I wasn't more clear, I am referring to Glyphs 3. There is no issue with Glyphs 2. But in Glyphs 3, the plugin manager is not using the correct `glyphs3` branch after I uninstall and reinstall. Only if I clone the repo from here and `git checkout glyphs3` manually — then it works

**Comment by schriftgestalt** [comment] 2021-08-16 10:48
Works for me. What version of Glyphs 3 do you have?
